/* Generated By:JavaCC: Do not edit this line. ArduinoDSLParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ArduinoDSLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ACENDER = 1;
  /** RegularExpression Id. */
  int APAGAR = 2;
  /** RegularExpression Id. */
  int ESPERAR = 3;
  /** RegularExpression Id. */
  int PINO = 4;
  /** RegularExpression Id. */
  int SEGUNDOS = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int SEMI = 7;
  /** RegularExpression Id. */
  int LINE_COMMENT = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"acender\"",
    "\"apagar\"",
    "\"esperar\"",
    "\"pino\"",
    "\"segundos\"",
    "<NUMBER>",
    "\";\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LINE_COMMENT>",
  };

}
