/* Generated By:JavaCC: Do not edit this line. ADSLVisitor.java Version 4.1d1 */
public interface ADSLVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTConfig node, Object data);
  public Object visit(ASTRepita node, Object data);
  public Object visit(ASTPinMode node, Object data);
  public Object visit(ASTPinos node, Object data);
  public Object visit(ASTPinosD node, Object data);
  public Object visit(ASTPinosA node, Object data);
  public Object visit(ASTPinosPWM node, Object data);
  public Object visit(ASTFreqMonitor node, Object data);
  public Object visit(ASTFrequencia node, Object data);
  public Object visit(ASTDelay node, Object data);
  public Object visit(ASTValorTempo node, Object data);
  public Object visit(ASTUnidadeTempo node, Object data);
  public Object visit(ASTRead node, Object data);
  public Object visit(ASTDigitalWrite node, Object data);
  public Object visit(ASTAnalogWrite node, Object data);
  public Object visit(ASTValorDigital node, Object data);
  public Object visit(ASTValorAnalogico node, Object data);
  public Object visit(ASTComando node, Object data);
  public Object visit(ASTSingleLineComment node, Object data);
  public Object visit(ASTMultiLineComment node, Object data);
  public Object visit(ASTFormalComment node, Object data);
  public Object visit(ASTSerialPrint node, Object data);
  public Object visit(ASTPrintContent node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTDecVar node, Object data);
  public Object visit(ASTTiposVar node, Object data);
  public Object visit(ASTInicializador node, Object data);
  public Object visit(ASTSeSenao node, Object data);
  public Object visit(ASTBlocoSe node, Object data);
  public Object visit(ASTBlocoSenao node, Object data);
  public Object visit(ASTCondicao node, Object data);
  public Object visit(ASTAtribuicao node, Object data);
  public Object visit(ASTExpressao node, Object data);
  public Object visit(ASTLeiaExpressao node, Object data);
  public Object visit(ASTValorNumerico node, Object data);
}
/* JavaCC - OriginalChecksum=700506b8c956efad871cb557c9128e38 (do not edit this line) */
