/* Generated By:JJTree&JavaCC: Do not edit this line. ADSL.java */
import java.io.*;

public class ADSL/*@bgen(jjtree)*/implements ADSLTreeConstants, ADSLConstants {/*@bgen(jjtree)*/
  protected JJTADSLState jjtree = new JJTADSLState();public static void main(String[] args) throws ParseException {
    if (args.length == 0) {
      System.err.println("Uso: java ADSL <arquivo.txt>");
      return;
    }

    try {
      FileInputStream input = new FileInputStream(args[0]);
      ADSL parser = new ADSL(input);
      SimpleNode root = parser.Start();
      root.jjtAccept(new ArduinoVisitor(), null);
    } catch (FileNotFoundException e) {
      System.err.println("Arquivo n\u00e3o encontrado: " + args[0]);
    }
  }

  final public SimpleNode Start() throws ParseException {
 /*@bgen(jjtree) Start */
  ASTStart jjtn000 = new ASTStart(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CONFIG:
        case REPITA:
        case SINGLE_LINE_COMMENT:
        case MULTI_LINE_COMMENT:
        case FORMAL_COMMENT:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CONFIG:
          Config();
          break;
        case REPITA:
          Repita();
          break;
        case SINGLE_LINE_COMMENT:
          SingleLineComment();
          break;
        case MULTI_LINE_COMMENT:
          MultiLineComment();
          break;
        case FORMAL_COMMENT:
          FormalComment();
          break;
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(0);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.jjtSetLastToken(getToken(0));
    {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void Config() throws ParseException {
 /*@bgen(jjtree) Config */
  ASTConfig jjtn000 = new ASTConfig(JJTCONFIG);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(CONFIG);
      jj_consume_token(LBRACE);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ENTRADA:
        case SAIDA:
        case MONITOR:
        case BYTE:
        case INT:
        case UNSIGNED_INT:
        case LONG:
        case UNSIGNED_LONG:
        case FLOAT:
        case CHAR:
        case STRING_TYPE:
        case BOOLEAN:
        case SINGLE_LINE_COMMENT:
        case MULTI_LINE_COMMENT:
        case FORMAL_COMMENT:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ENTRADA:
        case SAIDA:
          PinMode();
          break;
        case MONITOR:
          FreqMonitor();
          break;
        case BYTE:
        case INT:
        case UNSIGNED_INT:
        case LONG:
        case UNSIGNED_LONG:
        case FLOAT:
        case CHAR:
        case STRING_TYPE:
        case BOOLEAN:
          DecVar();
          break;
        case SINGLE_LINE_COMMENT:
          SingleLineComment();
          break;
        case MULTI_LINE_COMMENT:
          MultiLineComment();
          break;
        case FORMAL_COMMENT:
          FormalComment();
          break;
        default:
          jj_la1[3] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(RBRACE);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void Repita() throws ParseException {
 /*@bgen(jjtree) Repita */
  ASTRepita jjtn000 = new ASTRepita(JJTREPITA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(REPITA);
      jj_consume_token(LBRACE);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ENTRADA:
        case SAIDA:
        case ESPERA:
        case LEIA:
        case ESCREVA:
        case ESCREVA_PWM:
        case ESCRITA_MON:
        case SE:
        case BYTE:
        case INT:
        case UNSIGNED_INT:
        case LONG:
        case UNSIGNED_LONG:
        case FLOAT:
        case CHAR:
        case STRING_TYPE:
        case BOOLEAN:
        case IDENTIFIER:
        case SINGLE_LINE_COMMENT:
        case MULTI_LINE_COMMENT:
        case FORMAL_COMMENT:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_3;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ENTRADA:
        case SAIDA:
        case ESPERA:
        case LEIA:
        case ESCREVA:
        case ESCREVA_PWM:
        case ESCRITA_MON:
        case SE:
        case BYTE:
        case INT:
        case UNSIGNED_INT:
        case LONG:
        case UNSIGNED_LONG:
        case FLOAT:
        case CHAR:
        case STRING_TYPE:
        case BOOLEAN:
        case IDENTIFIER:
          Comando();
          break;
        case SINGLE_LINE_COMMENT:
          SingleLineComment();
          break;
        case MULTI_LINE_COMMENT:
          MultiLineComment();
          break;
        case FORMAL_COMMENT:
          FormalComment();
          break;
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(RBRACE);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void PinMode() throws ParseException {
 /*@bgen(jjtree) PinMode */
  ASTPinMode jjtn000 = new ASTPinMode(JJTPINMODE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ENTRADA:
        jj_consume_token(ENTRADA);
        break;
      case SAIDA:
        jj_consume_token(SAIDA);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Pinos();
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void Pinos() throws ParseException {
 /*@bgen(jjtree) Pinos */
  ASTPinos jjtn000 = new ASTPinos(JJTPINOS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM_INT:
        PinosD();
        break;
      case PINO_ANALOGICO:
        PinosA();
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void PinosD() throws ParseException {
 /*@bgen(jjtree) PinosD */
 ASTPinosD jjtn000 = new ASTPinosD(JJTPINOSD);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);
 jjtn000.jjtSetFirstToken(getToken(1));Token t;
    try {
      t = jj_consume_token(NUM_INT);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.jjtSetLastToken(getToken(0));
    // Validação para pinos digitais (0-19)
    int pino = Integer.parseInt(t.image);
    if (pino < 0 || pino > 19) {
      {if (true) throw new ParseException("Pino digital deve estar entre 0 e 19: " + pino);}
    }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void PinosA() throws ParseException {
 /*@bgen(jjtree) PinosA */
  ASTPinosA jjtn000 = new ASTPinosA(JJTPINOSA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(PINO_ANALOGICO);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void PinosPWM() throws ParseException {
 /*@bgen(jjtree) PinosPWM */
 ASTPinosPWM jjtn000 = new ASTPinosPWM(JJTPINOSPWM);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);
 jjtn000.jjtSetFirstToken(getToken(1));Token t;
    try {
      t = jj_consume_token(NUM_INT);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.jjtSetLastToken(getToken(0));
    // Validação para pinos PWM (3,5,6,9,10,11)
    int pino = Integer.parseInt(t.image);
    int[] pwmPins = {3,5,6,9,10,11};
    boolean isValid = false;
    for (int pin : pwmPins) {
      if (pino == pin) {
        isValid = true;
        break;
      }
    }
    if (!isValid) {
      {if (true) throw new ParseException("Pino PWM deve ser 3,5,6,9,10 ou 11: " + pino);}
    }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void FreqMonitor() throws ParseException {
 /*@bgen(jjtree) FreqMonitor */
  ASTFreqMonitor jjtn000 = new ASTFreqMonitor(JJTFREQMONITOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(MONITOR);
      Frequencia();
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void Frequencia() throws ParseException {
 /*@bgen(jjtree) Frequencia */
  ASTFrequencia jjtn000 = new ASTFrequencia(JJTFREQUENCIA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FREQ_300:
        jj_consume_token(FREQ_300);
        break;
      case FREQ_600:
        jj_consume_token(FREQ_600);
        break;
      case FREQ_1200:
        jj_consume_token(FREQ_1200);
        break;
      case FREQ_2400:
        jj_consume_token(FREQ_2400);
        break;
      case FREQ_4800:
        jj_consume_token(FREQ_4800);
        break;
      case FREQ_9600:
        jj_consume_token(FREQ_9600);
        break;
      case FREQ_14400:
        jj_consume_token(FREQ_14400);
        break;
      case FREQ_19200:
        jj_consume_token(FREQ_19200);
        break;
      case FREQ_28800:
        jj_consume_token(FREQ_28800);
        break;
      case FREQ_38400:
        jj_consume_token(FREQ_38400);
        break;
      case FREQ_57600:
        jj_consume_token(FREQ_57600);
        break;
      case FREQ_115200:
        jj_consume_token(FREQ_115200);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void Delay() throws ParseException {
 /*@bgen(jjtree) Delay */
  ASTDelay jjtn000 = new ASTDelay(JJTDELAY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(ESPERA);
      ValorTempo();
      UnidadeTempo();
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void ValorTempo() throws ParseException {
 /*@bgen(jjtree) ValorTempo */
 ASTValorTempo jjtn000 = new ASTValorTempo(JJTVALORTEMPO);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);
 jjtn000.jjtSetFirstToken(getToken(1));Token t;
    try {
      t = jj_consume_token(NUM_INT);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void UnidadeTempo() throws ParseException {
 /*@bgen(jjtree) UnidadeTempo */
  ASTUnidadeTempo jjtn000 = new ASTUnidadeTempo(JJTUNIDADETEMPO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NS:
        jj_consume_token(NS);
        break;
      case MS:
        jj_consume_token(MS);
        break;
      case S:
        jj_consume_token(S);
        break;
      case MIN:
        jj_consume_token(MIN);
        break;
      case H:
        jj_consume_token(H);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

// Comando de leitura unificado
  final public void Read() throws ParseException {
 /*@bgen(jjtree) Read */
  ASTRead jjtn000 = new ASTRead(JJTREAD);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(LEIA);
      Pinos();
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

// Comando de escrita digital unificado
  final public void DigitalWrite() throws ParseException {
 /*@bgen(jjtree) DigitalWrite */
  ASTDigitalWrite jjtn000 = new ASTDigitalWrite(JJTDIGITALWRITE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(ESCREVA);
      Pinos();
      ValorDigital();
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void AnalogWrite() throws ParseException {
 /*@bgen(jjtree) AnalogWrite */
  ASTAnalogWrite jjtn000 = new ASTAnalogWrite(JJTANALOGWRITE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(ESCREVA_PWM);
      PinosPWM();
      ValorAnalogico();
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void ValorDigital() throws ParseException {
 /*@bgen(jjtree) ValorDigital */
 ASTValorDigital jjtn000 = new ASTValorDigital(JJTVALORDIGITAL);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);
 jjtn000.jjtSetFirstToken(getToken(1));Token t;
    try {
      t = jj_consume_token(NUM_INT);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.jjtSetLastToken(getToken(0));
    // Validação para valores digitais (0 ou 1)
    int valor = Integer.parseInt(t.image);
    if (valor != 0 && valor != 1) {
      {if (true) throw new ParseException("Valor digital deve ser 0 ou 1: " + valor);}
    }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void ValorAnalogico() throws ParseException {
 /*@bgen(jjtree) ValorAnalogico */
 ASTValorAnalogico jjtn000 = new ASTValorAnalogico(JJTVALORANALOGICO);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);
 jjtn000.jjtSetFirstToken(getToken(1));Token t;
    try {
      t = jj_consume_token(NUM_INT);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.jjtSetLastToken(getToken(0));
    // Validação para valores analógicos/PWM (0-255)
    int valor = Integer.parseInt(t.image);
    if (valor < 0 || valor > 255) {
      {if (true) throw new ParseException("Valor PWM deve estar entre 0 e 255: " + valor);}
    }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void Comando() throws ParseException {
 /*@bgen(jjtree) Comando */
  ASTComando jjtn000 = new ASTComando(JJTCOMANDO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ENTRADA:
      case SAIDA:
        PinMode();
        break;
      case ESPERA:
        Delay();
        break;
      case LEIA:
        Read();
        break;
      case ESCREVA:
        DigitalWrite();
        break;
      case ESCREVA_PWM:
        AnalogWrite();
        break;
      case ESCRITA_MON:
        SerialPrint();
        break;
      case BYTE:
      case INT:
      case UNSIGNED_INT:
      case LONG:
      case UNSIGNED_LONG:
      case FLOAT:
      case CHAR:
      case STRING_TYPE:
      case BOOLEAN:
        DecVar();
        break;
      case SE:
        SeSenao();
        break;
      case IDENTIFIER:
        Atribuicao();
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void SingleLineComment() throws ParseException {
                                               /*@bgen(jjtree) SingleLineComment */
  ASTSingleLineComment jjtn000 = new ASTSingleLineComment(JJTSINGLELINECOMMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(SINGLE_LINE_COMMENT);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void MultiLineComment() throws ParseException {
                                             /*@bgen(jjtree) MultiLineComment */
  ASTMultiLineComment jjtn000 = new ASTMultiLineComment(JJTMULTILINECOMMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(MULTI_LINE_COMMENT);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void FormalComment() throws ParseException {
                                       /*@bgen(jjtree) FormalComment */
  ASTFormalComment jjtn000 = new ASTFormalComment(JJTFORMALCOMMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(FORMAL_COMMENT);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

// Comando de escrita no monitor serial
  final public void SerialPrint() throws ParseException {
 /*@bgen(jjtree) SerialPrint */
  ASTSerialPrint jjtn000 = new ASTSerialPrint(JJTSERIALPRINT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(ESCRITA_MON);
      jj_consume_token(LPAREN);
      PrintContent();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void PrintContent() throws ParseException {
 /*@bgen(jjtree) PrintContent */
 ASTPrintContent jjtn000 = new ASTPrintContent(JJTPRINTCONTENT);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);
 jjtn000.jjtSetFirstToken(getToken(1));Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        t = jj_consume_token(STRING);
        break;
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void String() throws ParseException {
 /*@bgen(jjtree) String */
 ASTString jjtn000 = new ASTString(JJTSTRING);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);
 jjtn000.jjtSetFirstToken(getToken(1));Token t;
    try {
      t = jj_consume_token(STRING);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

// Declaração de variáveis
  final public void DecVar() throws ParseException {
 /*@bgen(jjtree) DecVar */
  ASTDecVar jjtn000 = new ASTDecVar(JJTDECVAR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      TiposVar();
      jj_consume_token(IDENTIFIER);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 61:
        jj_consume_token(61);
        Inicializador();
        break;
      default:
        jj_la1[12] = jj_gen;
        ;
      }
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void TiposVar() throws ParseException {
 /*@bgen(jjtree) TiposVar */
  ASTTiposVar jjtn000 = new ASTTiposVar(JJTTIPOSVAR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BYTE:
        jj_consume_token(BYTE);
        break;
      case INT:
        jj_consume_token(INT);
        break;
      case UNSIGNED_INT:
        jj_consume_token(UNSIGNED_INT);
        break;
      case LONG:
        jj_consume_token(LONG);
        break;
      case UNSIGNED_LONG:
        jj_consume_token(UNSIGNED_LONG);
        break;
      case FLOAT:
        jj_consume_token(FLOAT);
        break;
      case CHAR:
        jj_consume_token(CHAR);
        break;
      case STRING_TYPE:
        jj_consume_token(STRING_TYPE);
        break;
      case BOOLEAN:
        jj_consume_token(BOOLEAN);
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void Inicializador() throws ParseException {
 /*@bgen(jjtree) Inicializador */
 ASTInicializador jjtn000 = new ASTInicializador(JJTINICIALIZADOR);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);
 jjtn000.jjtSetFirstToken(getToken(1));Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM_INT:
        t = jj_consume_token(NUM_INT);
        break;
      case NUM_FLT:
        t = jj_consume_token(NUM_FLT);
        break;
      case STRING:
        t = jj_consume_token(STRING);
        break;
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

// Estrutura condicional
  final public void SeSenao() throws ParseException {
 /*@bgen(jjtree) SeSenao */
  ASTSeSenao jjtn000 = new ASTSeSenao(JJTSESENAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(SE);
      jj_consume_token(LPAREN);
      Condicao();
      jj_consume_token(RPAREN);
      jj_consume_token(LBRACE);
      BlocoSe();
      jj_consume_token(RBRACE);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SENAO:
        jj_consume_token(SENAO);
        jj_consume_token(LBRACE);
        BlocoSenao();
        jj_consume_token(RBRACE);
        break;
      default:
        jj_la1[15] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void BlocoSe() throws ParseException {
 /*@bgen(jjtree) BlocoSe */
  ASTBlocoSe jjtn000 = new ASTBlocoSe(JJTBLOCOSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ENTRADA:
        case SAIDA:
        case ESPERA:
        case LEIA:
        case ESCREVA:
        case ESCREVA_PWM:
        case ESCRITA_MON:
        case SE:
        case BYTE:
        case INT:
        case UNSIGNED_INT:
        case LONG:
        case UNSIGNED_LONG:
        case FLOAT:
        case CHAR:
        case STRING_TYPE:
        case BOOLEAN:
        case IDENTIFIER:
        case SINGLE_LINE_COMMENT:
        case MULTI_LINE_COMMENT:
        case FORMAL_COMMENT:
          ;
          break;
        default:
          jj_la1[16] = jj_gen;
          break label_4;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ENTRADA:
        case SAIDA:
        case ESPERA:
        case LEIA:
        case ESCREVA:
        case ESCREVA_PWM:
        case ESCRITA_MON:
        case SE:
        case BYTE:
        case INT:
        case UNSIGNED_INT:
        case LONG:
        case UNSIGNED_LONG:
        case FLOAT:
        case CHAR:
        case STRING_TYPE:
        case BOOLEAN:
        case IDENTIFIER:
          Comando();
          break;
        case SINGLE_LINE_COMMENT:
          SingleLineComment();
          break;
        case MULTI_LINE_COMMENT:
          MultiLineComment();
          break;
        case FORMAL_COMMENT:
          FormalComment();
          break;
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void BlocoSenao() throws ParseException {
 /*@bgen(jjtree) BlocoSenao */
  ASTBlocoSenao jjtn000 = new ASTBlocoSenao(JJTBLOCOSENAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ENTRADA:
        case SAIDA:
        case ESPERA:
        case LEIA:
        case ESCREVA:
        case ESCREVA_PWM:
        case ESCRITA_MON:
        case SE:
        case BYTE:
        case INT:
        case UNSIGNED_INT:
        case LONG:
        case UNSIGNED_LONG:
        case FLOAT:
        case CHAR:
        case STRING_TYPE:
        case BOOLEAN:
        case IDENTIFIER:
        case SINGLE_LINE_COMMENT:
        case MULTI_LINE_COMMENT:
        case FORMAL_COMMENT:
          ;
          break;
        default:
          jj_la1[18] = jj_gen;
          break label_5;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ENTRADA:
        case SAIDA:
        case ESPERA:
        case LEIA:
        case ESCREVA:
        case ESCREVA_PWM:
        case ESCRITA_MON:
        case SE:
        case BYTE:
        case INT:
        case UNSIGNED_INT:
        case LONG:
        case UNSIGNED_LONG:
        case FLOAT:
        case CHAR:
        case STRING_TYPE:
        case BOOLEAN:
        case IDENTIFIER:
          Comando();
          break;
        case SINGLE_LINE_COMMENT:
          SingleLineComment();
          break;
        case MULTI_LINE_COMMENT:
          MultiLineComment();
          break;
        case FORMAL_COMMENT:
          FormalComment();
          break;
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void Condicao() throws ParseException {
 /*@bgen(jjtree) Condicao */
  ASTCondicao jjtn000 = new ASTCondicao(JJTCONDICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(IDENTIFIER);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

// Atribuição de variáveis
  final public void Atribuicao() throws ParseException {
 /*@bgen(jjtree) Atribuicao */
  ASTAtribuicao jjtn000 = new ASTAtribuicao(JJTATRIBUICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(IDENTIFIER);
      jj_consume_token(61);
      Expressao();
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void Expressao() throws ParseException {
 /*@bgen(jjtree) Expressao */
  ASTExpressao jjtn000 = new ASTExpressao(JJTEXPRESSAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEIA:
        LeiaExpressao();
        break;
      case NUM_FLT:
      case NUM_INT:
        ValorNumerico();
        break;
      case IDENTIFIER:
        jj_consume_token(IDENTIFIER);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void LeiaExpressao() throws ParseException {
 /*@bgen(jjtree) LeiaExpressao */
  ASTLeiaExpressao jjtn000 = new ASTLeiaExpressao(JJTLEIAEXPRESSAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(LEIA);
      Pinos();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  final public void ValorNumerico() throws ParseException {
 /*@bgen(jjtree) ValorNumerico */
 ASTValorNumerico jjtn000 = new ASTValorNumerico(JJTVALORNUMERICO);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);
 jjtn000.jjtSetFirstToken(getToken(1));Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM_INT:
        t = jj_consume_token(NUM_INT);
        break;
      case NUM_FLT:
        t = jj_consume_token(NUM_FLT);
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
      jjtn000.jjtSetLastToken(getToken(0));
    }
    }
  }

  /** Generated Token Manager. */
  public ADSLTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[22];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x6,0x6,0xc0000058,0xc0000058,0xc0000fb8,0xc0000fb8,0x18,0x0,0x3ffc0000,0x3e000,0xc0000fb8,0x0,0x0,0xc0000000,0x0,0x1000,0xc0000fb8,0xc0000fb8,0xc0000fb8,0xc0000fb8,0x80,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x7000,0x7000,0x707f,0x707f,0x787f,0x787f,0x0,0x300,0x0,0x0,0x87f,0xc00,0x20000000,0x7f,0xd80,0x0,0x787f,0x787f,0x787f,0x787f,0x980,0x180,};
   }

  /** Constructor with InputStream. */
  public ADSL(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ADSL(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ADSLTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public ADSL(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ADSLTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public ADSL(ADSLTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ADSLTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[62];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 22; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 62; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
