/* Generated By:JavaCC: Do not edit this line. ADSLVisitor.java Version 4.1d1 */
public interface ADSLVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTFuncao node, Object data);
  public Object visit(ASTParametros node, Object data);
  public Object visit(ASTParametro node, Object data);
  public Object visit(ASTTipoRetorno node, Object data);
  public Object visit(ASTRetorne node, Object data);
  public Object visit(ASTChamadaFuncao node, Object data);
  public Object visit(ASTArgumentos node, Object data);
  public Object visit(ASTConfig node, Object data);
  public Object visit(ASTExecute node, Object data);
  public Object visit(ASTPinMode node, Object data);
  public Object visit(ASTPinos node, Object data);
  public Object visit(ASTPinosD node, Object data);
  public Object visit(ASTPinosA node, Object data);
  public Object visit(ASTPinosPWM node, Object data);
  public Object visit(ASTFreqMonitor node, Object data);
  public Object visit(ASTFrequencia node, Object data);
  public Object visit(ASTDelay node, Object data);
  public Object visit(ASTValorTempo node, Object data);
  public Object visit(ASTUnidadeTempo node, Object data);
  public Object visit(ASTRead node, Object data);
  public Object visit(ASTDigitalWrite node, Object data);
  public Object visit(ASTAnalogWrite node, Object data);
  public Object visit(ASTValorDigital node, Object data);
  public Object visit(ASTValorAnalogico node, Object data);
  public Object visit(ASTRepita node, Object data);
  public Object visit(ASTBlocoRepita node, Object data);
  public Object visit(ASTComando node, Object data);
  public Object visit(ASTSingleLineComment node, Object data);
  public Object visit(ASTMultiLineComment node, Object data);
  public Object visit(ASTFormalComment node, Object data);
  public Object visit(ASTSerialPrint node, Object data);
  public Object visit(ASTDecVar node, Object data);
  public Object visit(ASTTiposVar node, Object data);
  public Object visit(ASTInicializador node, Object data);
  public Object visit(ASTSeSenao node, Object data);
  public Object visit(ASTBlocoSe node, Object data);
  public Object visit(ASTBlocoSenao node, Object data);
  public Object visit(ASTCondicao node, Object data);
  public Object visit(ASTAtribuicao node, Object data);
  public Object visit(ASTExpressao node, Object data);
  public Object visit(ASTExpressaoBooleana node, Object data);
  public Object visit(ASTExpressaoOu node, Object data);
  public Object visit(ASTExpressaoE node, Object data);
  public Object visit(ASTExpressaoRelacional node, Object data);
  public Object visit(ASTExpressaoAditiva node, Object data);
  public Object visit(ASTExpressaoMultiplicativa node, Object data);
  public Object visit(ASTExpressaoUnaria node, Object data);
  public Object visit(ASTExpressaoPrimaria node, Object data);
  public Object visit(ASTChamadaFuncaoExpressao node, Object data);
  public Object visit(ASTLeiaExpressao node, Object data);
  public Object visit(ASTValorNumerico node, Object data);
}
/* JavaCC - OriginalChecksum=168a709eaf7f0250e6a1d98401d9b4ae (do not edit this line) */
