/* Generated By:JJTree&JavaCC: Do not edit this line. ADSLTokenManager.java */
import java.io.*;

/** Token Manager. */
public class ADSLTokenManager implements ADSLConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x7ff80000L) != 0L)
         {
            jjmatchedKind = 63;
            return 31;
         }
         if ((active0 & 0x200000000000000L) != 0L)
            return 13;
         if ((active0 & 0x53000L) != 0L)
            return 6;
         if ((active0 & 0xff8002cffeL) != 0L)
         {
            jjmatchedKind = 66;
            return 6;
         }
         return -1;
      case 1:
         if ((active0 & 0x7ff80000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 63;
               jjmatchedPos = 1;
            }
            return 31;
         }
         if ((active0 & 0xf000L) != 0L)
            return 6;
         if ((active0 & 0xff80020ffeL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 1;
            }
            return 6;
         }
         return -1;
      case 2:
         if ((active0 & 0x100020000L) != 0L)
            return 6;
         if ((active0 & 0xfe80002ffeL) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 2;
            return 6;
         }
         if ((active0 & 0x7fe00000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 2;
            return 31;
         }
         if ((active0 & 0x180000L) != 0L)
            return 31;
         return -1;
      case 3:
         if ((active0 & 0x3480000100L) != 0L)
            return 6;
         if ((active0 & 0x7e000000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 3;
            return 31;
         }
         if ((active0 & 0xca00002efeL) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 3;
            return 6;
         }
         if ((active0 & 0x1e00000L) != 0L)
            return 31;
         return -1;
      case 4:
         if ((active0 & 0x2010L) != 0L)
            return 6;
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 4;
            return 31;
         }
         if ((active0 & 0xca00000eeeL) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 4;
            return 6;
         }
         if ((active0 & 0x3e000000L) != 0L)
            return 31;
         return -1;
      case 5:
         if ((active0 & 0x40000000a2L) != 0L)
            return 6;
         if ((active0 & 0x8a00000e4cL) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 5;
            return 6;
         }
         if ((active0 & 0x40000000L) != 0L)
            return 31;
         return -1;
      case 6:
         if ((active0 & 0x800000064cL) != 0L)
            return 6;
         if ((active0 & 0xa00000800L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 6;
            }
            return 6;
         }
         return -1;
      case 7:
         if ((active0 & 0xa00000c00L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 7;
            return 6;
         }
         return -1;
      case 8:
         if ((active0 & 0xa00000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0xc00L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 8;
            return 6;
         }
         return -1;
      case 9:
         if ((active0 & 0xc00L) != 0L)
            return 6;
         if ((active0 & 0xa00000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0xa00000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 11:
         if ((active0 & 0xa00000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 43;
         return jjMoveStringLiteralDfa1_0(0x4000000000000L);
      case 37:
         return jjStopAtPos(0, 61);
      case 38:
         jjmatchedKind = 58;
         return jjMoveStringLiteralDfa1_0(0x10000000000000L);
      case 40:
         return jjStopAtPos(0, 75);
      case 41:
         return jjStopAtPos(0, 76);
      case 42:
         return jjStopAtPos(0, 56);
      case 43:
         jjmatchedKind = 54;
         return jjMoveStringLiteralDfa1_0(0x20000000000000L);
      case 44:
         return jjStopAtPos(0, 82);
      case 45:
         return jjStopAtPos(0, 55);
      case 46:
         return jjStopAtPos(0, 83);
      case 47:
         return jjStartNfaWithStates_0(0, 57, 13);
      case 49:
         return jjMoveStringLiteralDfa1_0(0x46200000L);
      case 50:
         return jjMoveStringLiteralDfa1_0(0x8400000L);
      case 51:
         return jjMoveStringLiteralDfa1_0(0x10080000L);
      case 52:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 53:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 54:
         return jjMoveStringLiteralDfa1_0(0x100000L);
      case 57:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 58:
         return jjStopAtPos(0, 46);
      case 59:
         return jjStopAtPos(0, 81);
      case 60:
         jjmatchedKind = 42;
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 61:
         jjmatchedKind = 40;
         return jjMoveStringLiteralDfa1_0(0x800000000000L);
      case 62:
         jjmatchedKind = 41;
         return jjMoveStringLiteralDfa1_0(0x2000000000000L);
      case 63:
         return jjStopAtPos(0, 45);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x8000000000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x2L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0xe2cL);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x4000000010L);
      case 91:
         return jjStopAtPos(0, 79);
      case 93:
         return jjStopAtPos(0, 80);
      case 94:
         return jjStopAtPos(0, 60);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 104:
         return jjStartNfaWithStates_0(0, 18, 6);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x28000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x1000000080L);
      case 115:
         jjmatchedKind = 16;
         return jjMoveStringLiteralDfa1_0(0x3000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0xa00000000L);
      case 123:
         return jjStopAtPos(0, 77);
      case 124:
         jjmatchedKind = 59;
         return jjMoveStringLiteralDfa1_0(0x8000000000000L);
      case 125:
         return jjStopAtPos(0, 78);
      case 126:
         return jjStopAtPos(0, 44);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, 0L);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 52);
         break;
      case 43:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStopAtPos(1, 53);
         break;
      case 48:
         return jjMoveStringLiteralDfa2_0(active0, 0x180000L);
      case 49:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      case 50:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L);
      case 52:
         return jjMoveStringLiteralDfa2_0(active0, 0x2400000L);
      case 54:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 55:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 56:
         return jjMoveStringLiteralDfa2_0(active0, 0x18800000L);
      case 57:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 61:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(1, 47);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 48);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 49);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 50);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x10L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1000002180L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0xb00000008L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x8400000042L);
      case 115:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(1, 14, 6);
         else if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(1, 15, 6);
         return jjMoveStringLiteralDfa2_0(active0, 0xe20L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x4L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L);
      case 124:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(1, 51);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, 0L);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 48:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 19, 31);
         else if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 20, 31);
         return jjMoveStringLiteralDfa3_0(active0, 0x1e00000L);
      case 50:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 52:
         return jjMoveStringLiteralDfa3_0(active0, 0x12000000L);
      case 53:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 54:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 56:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0xe00L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x110L);
      case 110:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(2, 17, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x400002042L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0xa0L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0xa00000000L);
      case 116:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(2, 32, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x80000008L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, 0L);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 48:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 31);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 31);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 31);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 31);
         return jjMoveStringLiteralDfa4_0(active0, 0x3e000000L);
      case 50:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 97:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x4L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x10L);
      case 101:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 31, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x2L);
      case 103:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 6);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x4a000000c0L);
      case 108:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 36, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000L);
      case 114:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 37, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0xe08L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 48:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 25, 31);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 26, 31);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 31);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 31);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 31);
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      case 97:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x8L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000600L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0xa00000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x802L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L);
      case 111:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 13, 6);
         break;
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x20L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0xc0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 48:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 30, 31);
         break;
      case 97:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(5, 7, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x8L);
      case 101:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(5, 5, 6);
         break;
      case 103:
         if ((active0 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(5, 1, 6);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 6);
         break;
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0xa00000000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x40L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x804L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x600L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(6, 3, 6);
         else if ((active0 & 0x200L) != 0L)
         {
            jjmatchedKind = 9;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0xc00L);
      case 101:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(6, 2, 6);
         return jjMoveStringLiteralDfa7_0(active0, 0xa00000000L);
      case 110:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 39, 6);
         break;
      case 114:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(6, 6, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 77:
         return jjMoveStringLiteralDfa8_0(active0, 0x800L);
      case 80:
         return jjMoveStringLiteralDfa8_0(active0, 0x400L);
      case 100:
         return jjMoveStringLiteralDfa8_0(active0, 0xa00000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0xa00000000L);
      case 87:
         return jjMoveStringLiteralDfa9_0(active0, 0x400L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 77:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(9, 10, 6);
         break;
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000000L);
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000000L);
      case 110:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(9, 11, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x200000000L);
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000000L);
      case 116:
         if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(11, 33);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 103:
         if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(12, 35);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 31;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 63)
                        kind = 63;
                     jjCheckNAdd(11);
                  }
                  else if (curChar == 46)
                     jjCheckNAdd(10);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(8, 9);
                  break;
               case 13:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 24;
                  else if (curChar == 47)
                  {
                     if (kind > 67)
                        kind = 67;
                     jjCheckNAddStates(0, 2);
                  }
                  if (curChar == 42)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 63)
                        kind = 63;
                     jjCheckNAddStates(3, 5);
                  }
                  else if (curChar == 47)
                     jjAddStates(6, 8);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 1:
                  if ((0x3f000000000000L & l) != 0L && kind > 64)
                     kind = 64;
                  break;
               case 2:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 3:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 4:
                  if (curChar == 34 && kind > 65)
                     kind = 65;
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddStates(3, 5);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(8, 9);
                  break;
               case 9:
                  if (curChar == 46)
                     jjCheckNAdd(10);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjCheckNAdd(10);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(11);
                  break;
               case 12:
                  if (curChar == 47)
                     jjAddStates(6, 8);
                  break;
               case 14:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(0, 2);
                  break;
               case 15:
                  if ((0x2400L & l) != 0L && kind > 67)
                     kind = 67;
                  break;
               case 16:
                  if (curChar == 10 && kind > 67)
                     kind = 67;
                  break;
               case 17:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 19:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 20:
                  if (curChar == 42)
                     jjCheckNAddStates(9, 11);
                  break;
               case 21:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(22, 20);
                  break;
               case 22:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(22, 20);
                  break;
               case 23:
                  if (curChar == 47 && kind > 68)
                     kind = 68;
                  break;
               case 24:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 25:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 26:
                  if (curChar == 42)
                     jjCheckNAddStates(12, 14);
                  break;
               case 27:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               case 28:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               case 29:
                  if (curChar == 47 && kind > 69)
                     kind = 69;
                  break;
               case 30:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 66)
                        kind = 66;
                     jjCheckNAdd(6);
                  }
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  jjAddStates(15, 16);
                  break;
               case 5:
               case 6:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjCheckNAdd(6);
                  break;
               case 14:
                  if (kind > 67)
                     kind = 67;
                  jjAddStates(0, 2);
                  break;
               case 19:
                  jjCheckNAddTwoStates(19, 20);
                  break;
               case 21:
               case 22:
                  jjCheckNAddTwoStates(22, 20);
                  break;
               case 25:
                  jjCheckNAddTwoStates(25, 26);
                  break;
               case 27:
               case 28:
                  jjCheckNAddTwoStates(28, 26);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(15, 16);
                  break;
               case 14:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjAddStates(0, 2);
                  break;
               case 19:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 21:
               case 22:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(22, 20);
                  break;
               case 25:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 27:
               case 28:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 31 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   14, 15, 17, 8, 9, 11, 13, 18, 30, 20, 21, 23, 26, 27, 29, 3, 
   4, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\103\157\156\146\151\147", "\105\170\145\143\165\164\145", 
"\105\156\164\162\141\144\141", "\123\141\151\144\141", "\105\163\160\145\162\145", 
"\115\157\156\151\164\157\162", "\162\145\160\151\164\141", "\114\145\151\141", 
"\105\163\143\162\145\166\141", "\105\163\143\162\145\166\141\120\127\115", 
"\105\163\143\162\151\164\141\115\157\156", "\163\145", "\163\145\156\141\157", "\156\163", "\155\163", "\163", 
"\155\151\156", "\150", "\63\60\60", "\66\60\60", "\61\62\60\60", "\62\64\60\60", 
"\64\70\60\60", "\71\66\60\60", "\61\64\64\60\60", "\61\71\62\60\60", "\62\70\70\60\60", 
"\63\70\64\60\60", "\65\67\66\60\60", "\61\61\65\62\60\60", "\142\171\164\145", "\151\156\164", 
"\165\156\163\151\147\156\145\144\40\151\156\164", "\154\157\156\147", "\165\156\163\151\147\156\145\144\40\154\157\156\147", 
"\162\145\141\154", "\143\150\141\162", "\123\164\162\151\156\147", 
"\102\157\157\154\145\141\156", "\75", "\76", "\74", "\41", "\176", "\77", "\72", "\75\75", "\74\75", 
"\76\75", "\41\75", "\174\174", "\46\46", "\53\53", "\53", "\55", "\52", "\57", "\46", 
"\174", "\136", "\45", null, null, null, null, null, null, null, null, null, null, 
null, null, null, "\50", "\51", "\173", "\175", "\133", "\135", "\73", "\54", "\56", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xffffffffffffffffL, 0xff83fL, 
};
static final long[] jjtoSkip = {
   0x0L, 0x7c0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[31];
private final int[] jjstateSet = new int[62];
protected char curChar;
/** Constructor. */
public ADSLTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public ADSLTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 31; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
