/* Generated By:JJTree&JavaCC: Do not edit this line. ADSLTokenManager.java */
import java.io.*;

/** Token Manager. */
public class ADSLTokenManager implements ADSLConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x29800L) != 0L)
            return 6;
         if ((active0 & 0x7fc00167feL) != 0L)
         {
            jjmatchedKind = 43;
            return 6;
         }
         if ((active0 & 0x3ffc0000L) != 0L)
         {
            jjmatchedKind = 40;
            return 31;
         }
         return -1;
      case 1:
         if ((active0 & 0x7800L) != 0L)
            return 6;
         if ((active0 & 0x7fc00107feL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 1;
            }
            return 6;
         }
         if ((active0 & 0x3ffc0000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 1;
            }
            return 31;
         }
         return -1;
      case 2:
         if ((active0 & 0x80010000L) != 0L)
            return 6;
         if ((active0 & 0x3ff00000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 2;
            return 31;
         }
         if ((active0 & 0x7f400017feL) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 2;
            return 6;
         }
         if ((active0 & 0xc0000L) != 0L)
            return 31;
         return -1;
      case 3:
         if ((active0 & 0x1240000080L) != 0L)
            return 6;
         if ((active0 & 0x3f000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 3;
            return 31;
         }
         if ((active0 & 0xf00000L) != 0L)
            return 31;
         if ((active0 & 0x6d0000177eL) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 3;
            return 6;
         }
         return -1;
      case 4:
         if ((active0 & 0x650000076eL) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 4;
            return 6;
         }
         if ((active0 & 0x800001010L) != 0L)
            return 6;
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 4;
            return 31;
         }
         if ((active0 & 0x1f000000L) != 0L)
            return 31;
         return -1;
      case 5:
         if ((active0 & 0x4500000748L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 5;
            return 6;
         }
         if ((active0 & 0x2000000026L) != 0L)
            return 6;
         if ((active0 & 0x20000000L) != 0L)
            return 31;
         return -1;
      case 6:
         if ((active0 & 0x500000400L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 6;
            }
            return 6;
         }
         if ((active0 & 0x4000000348L) != 0L)
            return 6;
         return -1;
      case 7:
         if ((active0 & 0x500000600L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 7;
            return 6;
         }
         return -1;
      case 8:
         if ((active0 & 0x600L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 8;
            return 6;
         }
         if ((active0 & 0x500000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0x600L) != 0L)
            return 6;
         if ((active0 & 0x500000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x500000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 11:
         if ((active0 & 0x500000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 52);
      case 41:
         return jjStopAtPos(0, 53);
      case 44:
         return jjStopAtPos(0, 59);
      case 46:
         return jjStopAtPos(0, 60);
      case 49:
         return jjMoveStringLiteralDfa1_0(0x23100000L);
      case 50:
         return jjMoveStringLiteralDfa1_0(0x4200000L);
      case 51:
         return jjMoveStringLiteralDfa1_0(0x8040000L);
      case 52:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 53:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 54:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 57:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 59:
         return jjStopAtPos(0, 58);
      case 61:
         return jjStopAtPos(0, 61);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x2L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x728L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x4L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x2000000010L);
      case 91:
         return jjStopAtPos(0, 56);
      case 93:
         return jjStopAtPos(0, 57);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1000000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 104:
         return jjStartNfaWithStates_0(0, 17, 6);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x200000000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x14000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 115:
         jjmatchedKind = 15;
         return jjMoveStringLiteralDfa1_0(0x1800L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x500000000L);
      case 123:
         return jjStopAtPos(0, 54);
      case 125:
         return jjStopAtPos(0, 55);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 48:
         return jjMoveStringLiteralDfa2_0(active0, 0xc0000L);
      case 49:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 50:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L);
      case 52:
         return jjMoveStringLiteralDfa2_0(active0, 0x1200000L);
      case 54:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
      case 55:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
      case 56:
         return jjMoveStringLiteralDfa2_0(active0, 0xc400000L);
      case 57:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x10L);
      case 101:
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1084L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x580000008L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x4200000042L);
      case 115:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(1, 13, 6);
         else if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(1, 14, 6);
         return jjMoveStringLiteralDfa2_0(active0, 0x720L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 48:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(2, 18, 31);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 19, 31);
         return jjMoveStringLiteralDfa3_0(active0, 0xf00000L);
      case 50:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 52:
         return jjMoveStringLiteralDfa3_0(active0, 0x9000000L);
      case 53:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 54:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 56:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x700L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x90L);
      case 110:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(2, 16, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x200001042L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4800000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x24L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x500000000L);
      case 116:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(2, 31, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x40000008L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 48:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 31);
         else if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 31);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 31);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 31);
         return jjMoveStringLiteralDfa4_0(active0, 0x1f000000L);
      case 50:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 97:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 7, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x800001000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x10L);
      case 101:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x2L);
      case 103:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 6);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x2500000044L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
      case 114:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 36, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x708L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 48:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(4, 24, 31);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 25, 31);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 26, 31);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 31);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 31);
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 97:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x8L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000300L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x500000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x402L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000L);
      case 111:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 6);
         break;
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x20L);
      case 116:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(4, 35, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x44L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 48:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 31);
         break;
      case 97:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(5, 2, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x8L);
      case 101:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(5, 5, 6);
         break;
      case 103:
         if ((active0 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(5, 1, 6);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 37, 6);
         break;
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x500000000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x40L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x300L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(6, 3, 6);
         else if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 8;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x600L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x500000000L);
      case 110:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 38, 6);
         break;
      case 114:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(6, 6, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 77:
         return jjMoveStringLiteralDfa8_0(active0, 0x400L);
      case 80:
         return jjMoveStringLiteralDfa8_0(active0, 0x200L);
      case 100:
         return jjMoveStringLiteralDfa8_0(active0, 0x500000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0x500000000L);
      case 87:
         return jjMoveStringLiteralDfa9_0(active0, 0x200L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 77:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(9, 9, 6);
         break;
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000L);
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000000L);
      case 110:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(9, 10, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000000L);
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000000L);
      case 116:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(11, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 103:
         if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(12, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 31;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAdd(11);
                  }
                  else if (curChar == 46)
                     jjCheckNAdd(10);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(8, 9);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAddStates(0, 2);
                  }
                  else if (curChar == 47)
                     jjAddStates(3, 5);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 1:
                  if ((0x3f000000000000L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 2:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 3:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 4:
                  if (curChar == 34 && kind > 42)
                     kind = 42;
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddStates(0, 2);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(8, 9);
                  break;
               case 9:
                  if (curChar == 46)
                     jjCheckNAdd(10);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 39)
                     kind = 39;
                  jjCheckNAdd(10);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAdd(11);
                  break;
               case 12:
                  if (curChar == 47)
                     jjAddStates(3, 5);
                  break;
               case 13:
                  if (curChar != 47)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddStates(6, 8);
                  break;
               case 14:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddStates(6, 8);
                  break;
               case 15:
                  if ((0x2400L & l) != 0L && kind > 44)
                     kind = 44;
                  break;
               case 16:
                  if (curChar == 10 && kind > 44)
                     kind = 44;
                  break;
               case 17:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 19:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 20:
                  if (curChar == 42)
                     jjCheckNAddStates(9, 11);
                  break;
               case 21:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(22, 20);
                  break;
               case 22:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(22, 20);
                  break;
               case 23:
                  if (curChar == 47 && kind > 45)
                     kind = 45;
                  break;
               case 24:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 25:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 26:
                  if (curChar == 42)
                     jjCheckNAddStates(12, 14);
                  break;
               case 27:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               case 28:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               case 29:
                  if (curChar == 47 && kind > 46)
                     kind = 46;
                  break;
               case 30:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(6);
                  }
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  jjAddStates(15, 16);
                  break;
               case 5:
               case 6:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAdd(6);
                  break;
               case 14:
                  if (kind > 44)
                     kind = 44;
                  jjAddStates(6, 8);
                  break;
               case 19:
                  jjCheckNAddTwoStates(19, 20);
                  break;
               case 21:
               case 22:
                  jjCheckNAddTwoStates(22, 20);
                  break;
               case 25:
                  jjCheckNAddTwoStates(25, 26);
                  break;
               case 27:
               case 28:
                  jjCheckNAddTwoStates(28, 26);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(15, 16);
                  break;
               case 14:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjAddStates(6, 8);
                  break;
               case 19:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 21:
               case 22:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(22, 20);
                  break;
               case 25:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 27:
               case 28:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 31 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   8, 9, 11, 13, 18, 30, 14, 15, 17, 20, 21, 23, 26, 27, 29, 3, 
   4, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\103\157\156\146\151\147", "\122\145\160\151\164\141", 
"\105\156\164\162\141\144\141", "\123\141\151\144\141", "\105\163\160\145\162\145", 
"\115\157\156\151\164\157\162", "\114\145\151\141", "\105\163\143\162\145\166\141", 
"\105\163\143\162\145\166\141\120\127\115", "\105\163\143\162\151\164\141\115\157\156", "\163\145", 
"\163\145\156\141\157", "\156\163", "\155\163", "\163", "\155\151\156", "\150", "\63\60\60", 
"\66\60\60", "\61\62\60\60", "\62\64\60\60", "\64\70\60\60", "\71\66\60\60", 
"\61\64\64\60\60", "\61\71\62\60\60", "\62\70\70\60\60", "\63\70\64\60\60", "\65\67\66\60\60", 
"\61\61\65\62\60\60", "\142\171\164\145", "\151\156\164", 
"\165\156\163\151\147\156\145\144\40\151\156\164", "\154\157\156\147", "\165\156\163\151\147\156\145\144\40\154\157\156\147", 
"\146\154\157\141\164", "\143\150\141\162", "\123\164\162\151\156\147", 
"\102\157\157\154\145\141\156", null, null, null, null, null, null, null, null, null, null, null, null, null, 
"\50", "\51", "\173", "\175", "\133", "\135", "\73", "\54", "\56", "\75", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x3ff07fffffffffffL, 
};
static final long[] jjtoSkip = {
   0xf800000000000L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[31];
private final int[] jjstateSet = new int[62];
protected char curChar;
/** Constructor. */
public ADSLTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public ADSLTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 31; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
