/* Generated By:JavaCC: Do not edit this line. ADSLTreeConstants.java Version 4.1d1 */
public interface ADSLTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFUNCAO = 1;
  public int JJTPARAMETROS = 2;
  public int JJTPARAMETRO = 3;
  public int JJTTIPORETORNO = 4;
  public int JJTRETORNE = 5;
  public int JJTCHAMADAFUNCAO = 6;
  public int JJTARGUMENTOS = 7;
  public int JJTCONFIG = 8;
  public int JJTEXECUTE = 9;
  public int JJTPINMODE = 10;
  public int JJTPINOS = 11;
  public int JJTPINOSD = 12;
  public int JJTPINOSA = 13;
  public int JJTPINOSPWM = 14;
  public int JJTFREQMONITOR = 15;
  public int JJTFREQUENCIA = 16;
  public int JJTDELAY = 17;
  public int JJTVALORTEMPO = 18;
  public int JJTUNIDADETEMPO = 19;
  public int JJTREAD = 20;
  public int JJTDIGITALWRITE = 21;
  public int JJTANALOGWRITE = 22;
  public int JJTVALORDIGITAL = 23;
  public int JJTVALORANALOGICO = 24;
  public int JJTREPITA = 25;
  public int JJTBLOCOREPITA = 26;
  public int JJTCOMANDO = 27;
  public int JJTSINGLELINECOMMENT = 28;
  public int JJTMULTILINECOMMENT = 29;
  public int JJTFORMALCOMMENT = 30;
  public int JJTSERIALPRINT = 31;
  public int JJTDECVAR = 32;
  public int JJTTIPOSVAR = 33;
  public int JJTINICIALIZADOR = 34;
  public int JJTSESENAO = 35;
  public int JJTBLOCOSE = 36;
  public int JJTBLOCOSENAO = 37;
  public int JJTCONDICAO = 38;
  public int JJTATRIBUICAO = 39;
  public int JJTEXPRESSAO = 40;
  public int JJTEXPRESSAOBOOLEANA = 41;
  public int JJTEXPRESSAOOU = 42;
  public int JJTEXPRESSAOE = 43;
  public int JJTEXPRESSAORELACIONAL = 44;
  public int JJTEXPRESSAOADITIVA = 45;
  public int JJTEXPRESSAOMULTIPLICATIVA = 46;
  public int JJTEXPRESSAOUNARIA = 47;
  public int JJTEXPRESSAOPRIMARIA = 48;
  public int JJTCHAMADAFUNCAOEXPRESSAO = 49;
  public int JJTLEIAEXPRESSAO = 50;
  public int JJTVALORNUMERICO = 51;


  public String[] jjtNodeName = {
    "Start",
    "Funcao",
    "Parametros",
    "Parametro",
    "TipoRetorno",
    "Retorne",
    "ChamadaFuncao",
    "Argumentos",
    "Config",
    "Execute",
    "PinMode",
    "Pinos",
    "PinosD",
    "PinosA",
    "PinosPWM",
    "FreqMonitor",
    "Frequencia",
    "Delay",
    "ValorTempo",
    "UnidadeTempo",
    "Read",
    "DigitalWrite",
    "AnalogWrite",
    "ValorDigital",
    "ValorAnalogico",
    "Repita",
    "BlocoRepita",
    "Comando",
    "SingleLineComment",
    "MultiLineComment",
    "FormalComment",
    "SerialPrint",
    "DecVar",
    "TiposVar",
    "Inicializador",
    "SeSenao",
    "BlocoSe",
    "BlocoSenao",
    "Condicao",
    "Atribuicao",
    "Expressao",
    "ExpressaoBooleana",
    "ExpressaoOu",
    "ExpressaoE",
    "ExpressaoRelacional",
    "ExpressaoAditiva",
    "ExpressaoMultiplicativa",
    "ExpressaoUnaria",
    "ExpressaoPrimaria",
    "ChamadaFuncaoExpressao",
    "LeiaExpressao",
    "ValorNumerico",
  };
}
/* JavaCC - OriginalChecksum=13311ea1442c7cef612b589fb491fabc (do not edit this line) */
