/* Generated By:JJTree&JavaCC: Do not edit this line. ADSLConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ADSLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONFIG = 1;
  /** RegularExpression Id. */
  int REPITA = 2;
  /** RegularExpression Id. */
  int ENTRADA = 3;
  /** RegularExpression Id. */
  int SAIDA = 4;
  /** RegularExpression Id. */
  int ESPERA = 5;
  /** RegularExpression Id. */
  int MONITOR = 6;
  /** RegularExpression Id. */
  int LEIA = 7;
  /** RegularExpression Id. */
  int ESCREVA = 8;
  /** RegularExpression Id. */
  int ESCREVA_PWM = 9;
  /** RegularExpression Id. */
  int ESCRITA_MON = 10;
  /** RegularExpression Id. */
  int NS = 11;
  /** RegularExpression Id. */
  int MS = 12;
  /** RegularExpression Id. */
  int S = 13;
  /** RegularExpression Id. */
  int MIN = 14;
  /** RegularExpression Id. */
  int H = 15;
  /** RegularExpression Id. */
  int FREQ_300 = 16;
  /** RegularExpression Id. */
  int FREQ_600 = 17;
  /** RegularExpression Id. */
  int FREQ_1200 = 18;
  /** RegularExpression Id. */
  int FREQ_2400 = 19;
  /** RegularExpression Id. */
  int FREQ_4800 = 20;
  /** RegularExpression Id. */
  int FREQ_9600 = 21;
  /** RegularExpression Id. */
  int FREQ_14400 = 22;
  /** RegularExpression Id. */
  int FREQ_19200 = 23;
  /** RegularExpression Id. */
  int FREQ_28800 = 24;
  /** RegularExpression Id. */
  int FREQ_38400 = 25;
  /** RegularExpression Id. */
  int FREQ_57600 = 26;
  /** RegularExpression Id. */
  int FREQ_115200 = 27;
  /** RegularExpression Id. */
  int BYTE = 28;
  /** RegularExpression Id. */
  int INT = 29;
  /** RegularExpression Id. */
  int UNSIGNED_INT = 30;
  /** RegularExpression Id. */
  int LONG = 31;
  /** RegularExpression Id. */
  int UNSIGNED_LONG = 32;
  /** RegularExpression Id. */
  int FLOAT = 33;
  /** RegularExpression Id. */
  int CHAR = 34;
  /** RegularExpression Id. */
  int STRING_TYPE = 35;
  /** RegularExpression Id. */
  int BOOLEAN = 36;
  /** RegularExpression Id. */
  int NUM_FLT = 37;
  /** RegularExpression Id. */
  int NUM_INT = 38;
  /** RegularExpression Id. */
  int PINO_ANALOGICO = 39;
  /** RegularExpression Id. */
  int STRING = 40;
  /** RegularExpression Id. */
  int IDENTIFIER = 41;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 42;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 43;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 44;
  /** RegularExpression Id. */
  int LPAREN = 50;
  /** RegularExpression Id. */
  int RPAREN = 51;
  /** RegularExpression Id. */
  int LBRACE = 52;
  /** RegularExpression Id. */
  int RBRACE = 53;
  /** RegularExpression Id. */
  int LBRACKET = 54;
  /** RegularExpression Id. */
  int RBRACKET = 55;
  /** RegularExpression Id. */
  int SEMICOLON = 56;
  /** RegularExpression Id. */
  int COMMA = 57;
  /** RegularExpression Id. */
  int DOT = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Config\"",
    "\"Repita\"",
    "\"Entrada\"",
    "\"Saida\"",
    "\"Espere\"",
    "\"Monitor\"",
    "\"Leia\"",
    "\"Escreva\"",
    "\"EscrevaPWM\"",
    "\"EscritaMon\"",
    "\"ns\"",
    "\"ms\"",
    "\"s\"",
    "\"min\"",
    "\"h\"",
    "\"300\"",
    "\"600\"",
    "\"1200\"",
    "\"2400\"",
    "\"4800\"",
    "\"9600\"",
    "\"14400\"",
    "\"19200\"",
    "\"28800\"",
    "\"38400\"",
    "\"57600\"",
    "\"115200\"",
    "\"byte\"",
    "\"int\"",
    "\"unsigned int\"",
    "\"long\"",
    "\"unsigned long\"",
    "\"float\"",
    "\"char\"",
    "\"String\"",
    "\"Boolean\"",
    "<NUM_FLT>",
    "<NUM_INT>",
    "<PINO_ANALOGICO>",
    "<STRING>",
    "<IDENTIFIER>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
  };

}
