/* Generated By:JavaCC: Do not edit this line. ADSLTreeConstants.java Version 4.1d1 */
public interface ADSLTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCONFIG = 1;
  public int JJTEXECUTE = 2;
  public int JJTPINMODE = 3;
  public int JJTPINOS = 4;
  public int JJTPINOSD = 5;
  public int JJTPINOSA = 6;
  public int JJTPINOSPWM = 7;
  public int JJTFREQMONITOR = 8;
  public int JJTFREQUENCIA = 9;
  public int JJTDELAY = 10;
  public int JJTVALORTEMPO = 11;
  public int JJTUNIDADETEMPO = 12;
  public int JJTREAD = 13;
  public int JJTDIGITALWRITE = 14;
  public int JJTANALOGWRITE = 15;
  public int JJTVALORDIGITAL = 16;
  public int JJTVALORANALOGICO = 17;
  public int JJTREPITA = 18;
  public int JJTBLOCOREPITA = 19;
  public int JJTCOMANDO = 20;
  public int JJTSINGLELINECOMMENT = 21;
  public int JJTMULTILINECOMMENT = 22;
  public int JJTFORMALCOMMENT = 23;
  public int JJTSERIALPRINT = 24;
  public int JJTPRINTCONTENT = 25;
  public int JJTSTRING = 26;
  public int JJTDECVAR = 27;
  public int JJTTIPOSVAR = 28;
  public int JJTINICIALIZADOR = 29;
  public int JJTSESENAO = 30;
  public int JJTBLOCOSE = 31;
  public int JJTBLOCOSENAO = 32;
  public int JJTCONDICAO = 33;
  public int JJTATRIBUICAO = 34;
  public int JJTEXPRESSAO = 35;
  public int JJTEXPRESSAOBOOLEANA = 36;
  public int JJTEXPRESSAOOU = 37;
  public int JJTEXPRESSAOE = 38;
  public int JJTEXPRESSAORELACIONAL = 39;
  public int JJTEXPRESSAOADITIVA = 40;
  public int JJTEXPRESSAOMULTIPLICATIVA = 41;
  public int JJTEXPRESSAOUNARIA = 42;
  public int JJTEXPRESSAOPRIMARIA = 43;
  public int JJTLEIAEXPRESSAO = 44;
  public int JJTVALORNUMERICO = 45;


  public String[] jjtNodeName = {
    "Start",
    "Config",
    "Execute",
    "PinMode",
    "Pinos",
    "PinosD",
    "PinosA",
    "PinosPWM",
    "FreqMonitor",
    "Frequencia",
    "Delay",
    "ValorTempo",
    "UnidadeTempo",
    "Read",
    "DigitalWrite",
    "AnalogWrite",
    "ValorDigital",
    "ValorAnalogico",
    "Repita",
    "BlocoRepita",
    "Comando",
    "SingleLineComment",
    "MultiLineComment",
    "FormalComment",
    "SerialPrint",
    "PrintContent",
    "String",
    "DecVar",
    "TiposVar",
    "Inicializador",
    "SeSenao",
    "BlocoSe",
    "BlocoSenao",
    "Condicao",
    "Atribuicao",
    "Expressao",
    "ExpressaoBooleana",
    "ExpressaoOu",
    "ExpressaoE",
    "ExpressaoRelacional",
    "ExpressaoAditiva",
    "ExpressaoMultiplicativa",
    "ExpressaoUnaria",
    "ExpressaoPrimaria",
    "LeiaExpressao",
    "ValorNumerico",
  };
}
/* JavaCC - OriginalChecksum=27c14da0f11167c7c0439de950855c0e (do not edit this line) */
