/* Generated By:JJTree&JavaCC: Do not edit this line. ADSLConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ADSLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONFIG = 1;
  /** RegularExpression Id. */
  int REPITA = 2;
  /** RegularExpression Id. */
  int ENTRADA = 3;
  /** RegularExpression Id. */
  int SAIDA = 4;
  /** RegularExpression Id. */
  int ESPERA = 5;
  /** RegularExpression Id. */
  int MONITOR = 6;
  /** RegularExpression Id. */
  int LEIA = 7;
  /** RegularExpression Id. */
  int ESCREVA = 8;
  /** RegularExpression Id. */
  int ESCREVA_PWM = 9;
  /** RegularExpression Id. */
  int ESCRITA_MON = 10;
  /** RegularExpression Id. */
  int SE = 11;
  /** RegularExpression Id. */
  int SENAO = 12;
  /** RegularExpression Id. */
  int NS = 13;
  /** RegularExpression Id. */
  int MS = 14;
  /** RegularExpression Id. */
  int S = 15;
  /** RegularExpression Id. */
  int MIN = 16;
  /** RegularExpression Id. */
  int H = 17;
  /** RegularExpression Id. */
  int FREQ_300 = 18;
  /** RegularExpression Id. */
  int FREQ_600 = 19;
  /** RegularExpression Id. */
  int FREQ_1200 = 20;
  /** RegularExpression Id. */
  int FREQ_2400 = 21;
  /** RegularExpression Id. */
  int FREQ_4800 = 22;
  /** RegularExpression Id. */
  int FREQ_9600 = 23;
  /** RegularExpression Id. */
  int FREQ_14400 = 24;
  /** RegularExpression Id. */
  int FREQ_19200 = 25;
  /** RegularExpression Id. */
  int FREQ_28800 = 26;
  /** RegularExpression Id. */
  int FREQ_38400 = 27;
  /** RegularExpression Id. */
  int FREQ_57600 = 28;
  /** RegularExpression Id. */
  int FREQ_115200 = 29;
  /** RegularExpression Id. */
  int BYTE = 30;
  /** RegularExpression Id. */
  int INT = 31;
  /** RegularExpression Id. */
  int UNSIGNED_INT = 32;
  /** RegularExpression Id. */
  int LONG = 33;
  /** RegularExpression Id. */
  int UNSIGNED_LONG = 34;
  /** RegularExpression Id. */
  int FLOAT = 35;
  /** RegularExpression Id. */
  int CHAR = 36;
  /** RegularExpression Id. */
  int STRING_TYPE = 37;
  /** RegularExpression Id. */
  int BOOLEAN = 38;
  /** RegularExpression Id. */
  int ASSIGN = 39;
  /** RegularExpression Id. */
  int GT = 40;
  /** RegularExpression Id. */
  int LT = 41;
  /** RegularExpression Id. */
  int BANG = 42;
  /** RegularExpression Id. */
  int TILDE = 43;
  /** RegularExpression Id. */
  int HOOK = 44;
  /** RegularExpression Id. */
  int COLON = 45;
  /** RegularExpression Id. */
  int EQ = 46;
  /** RegularExpression Id. */
  int LE = 47;
  /** RegularExpression Id. */
  int GE = 48;
  /** RegularExpression Id. */
  int NE = 49;
  /** RegularExpression Id. */
  int SC_OR = 50;
  /** RegularExpression Id. */
  int SC_AND = 51;
  /** RegularExpression Id. */
  int CONCAT = 52;
  /** RegularExpression Id. */
  int PLUS = 53;
  /** RegularExpression Id. */
  int MINUS = 54;
  /** RegularExpression Id. */
  int STAR = 55;
  /** RegularExpression Id. */
  int SLASH = 56;
  /** RegularExpression Id. */
  int BIT_AND = 57;
  /** RegularExpression Id. */
  int BIT_OR = 58;
  /** RegularExpression Id. */
  int XOR = 59;
  /** RegularExpression Id. */
  int REM = 60;
  /** RegularExpression Id. */
  int NUM_FLT = 61;
  /** RegularExpression Id. */
  int NUM_INT = 62;
  /** RegularExpression Id. */
  int PINO_ANALOGICO = 63;
  /** RegularExpression Id. */
  int STRING = 64;
  /** RegularExpression Id. */
  int IDENTIFIER = 65;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 66;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 67;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 68;
  /** RegularExpression Id. */
  int LPAREN = 74;
  /** RegularExpression Id. */
  int RPAREN = 75;
  /** RegularExpression Id. */
  int LBRACE = 76;
  /** RegularExpression Id. */
  int RBRACE = 77;
  /** RegularExpression Id. */
  int LBRACKET = 78;
  /** RegularExpression Id. */
  int RBRACKET = 79;
  /** RegularExpression Id. */
  int SEMICOLON = 80;
  /** RegularExpression Id. */
  int COMMA = 81;
  /** RegularExpression Id. */
  int DOT = 82;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Config\"",
    "\"Repita\"",
    "\"Entrada\"",
    "\"Saida\"",
    "\"Espere\"",
    "\"Monitor\"",
    "\"Leia\"",
    "\"Escreva\"",
    "\"EscrevaPWM\"",
    "\"EscritaMon\"",
    "\"se\"",
    "\"senao\"",
    "\"ns\"",
    "\"ms\"",
    "\"s\"",
    "\"min\"",
    "\"h\"",
    "\"300\"",
    "\"600\"",
    "\"1200\"",
    "\"2400\"",
    "\"4800\"",
    "\"9600\"",
    "\"14400\"",
    "\"19200\"",
    "\"28800\"",
    "\"38400\"",
    "\"57600\"",
    "\"115200\"",
    "\"byte\"",
    "\"int\"",
    "\"unsigned int\"",
    "\"long\"",
    "\"unsigned long\"",
    "\"real\"",
    "\"char\"",
    "\"String\"",
    "\"Boolean\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "<NUM_FLT>",
    "<NUM_INT>",
    "<PINO_ANALOGICO>",
    "<STRING>",
    "<IDENTIFIER>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
  };

}
