/* Generated By:JavaCC: Do not edit this line. ADSLVisitor.java Version 4.1d1 */
public interface ADSLVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTConfig node, Object data);
  public Object visit(ASTRepita node, Object data);
  public Object visit(ASTPinMode node, Object data);
  public Object visit(ASTPinos node, Object data);
  public Object visit(ASTPinosD node, Object data);
  public Object visit(ASTPinosA node, Object data);
  public Object visit(ASTPinosPWM node, Object data);
  public Object visit(ASTFreqMonitor node, Object data);
  public Object visit(ASTFrequencia node, Object data);
  public Object visit(ASTDelay node, Object data);
  public Object visit(ASTValorTempo node, Object data);
  public Object visit(ASTUnidadeTempo node, Object data);
  public Object visit(ASTComando node, Object data);
  public Object visit(ASTSingleLineComment node, Object data);
  public Object visit(ASTMultiLineComment node, Object data);
  public Object visit(ASTFormalComment node, Object data);
}
/* JavaCC - OriginalChecksum=0ef0d616c019eae8ec314fe7e457394c (do not edit this line) */
