/* Generated By:JJTree: Do not edit this line. ASTAnalogWrite.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAnalogWrite extends SimpleNode {
  public ASTAnalogWrite(int id) {
    super(id);
  }

  public ASTAnalogWrite(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8d042325c1705eb9da02d0c22857d94f (do not edit this line) */
