/* Generated By:JJTree: Do not edit this line. ASTAnalogRead.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAnalogRead extends SimpleNode {
  public ASTAnalogRead(int id) {
    super(id);
  }

  public ASTAnalogRead(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=998ccd6af80ac33561aab1d4a7c362f3 (do not edit this line) */
