/* Generated By:JJTree: Do not edit this line. ASTBlocoRepita.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTBlocoRepita extends SimpleNode {
  public ASTBlocoRepita(int id) {
    super(id);
  }

  public ASTBlocoRepita(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=18e9414ef26cb87b584f84631f26370e (do not edit this line) */
