/* Generated By:JJTree: Do not edit this line. ASTBlocoSenao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTBlocoSenao extends SimpleNode {
  public ASTBlocoSenao(int id) {
    super(id);
  }

  public ASTBlocoSenao(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=08055f757da3e90edc58e49e97345241 (do not edit this line) */
