/* Generated By:JJTree: Do not edit this line. ASTChamadaFuncaoExpressao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTChamadaFuncaoExpressao extends SimpleNode {
  public ASTChamadaFuncaoExpressao(int id) {
    super(id);
  }

  public ASTChamadaFuncaoExpressao(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=16b34fd73c5defca783e3a2569bfedb4 (do not edit this line) */
