/* Generated By:JJTree: Do not edit this line. ASTComando.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTComando extends SimpleNode {
  public ASTComando(int id) {
    super(id);
  }

  public ASTComando(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=08c59538110a365b3d7854611d0dd67f (do not edit this line) */
