/* Generated By:JJTree: Do not edit this line. ASTDigitalWrite.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDigitalWrite extends SimpleNode {
  public ASTDigitalWrite(int id) {
    super(id);
  }

  public ASTDigitalWrite(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c68f0679cbc4c53a1e2d3f343767b985 (do not edit this line) */
