/* Generated By:JJTree: Do not edit this line. ASTDigitalRead.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDigitalRead extends SimpleNode {
  public ASTDigitalRead(int id) {
    super(id);
  }

  public ASTDigitalRead(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3ae58ef26d4978e1710bb2ab77be5380 (do not edit this line) */
