/* Generated By:JJTree: Do not edit this line. ASTDecVar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDecVar extends SimpleNode {
  public ASTDecVar(int id) {
    super(id);
  }

  public ASTDecVar(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d7379e3cec12832eca463cd8b1c072a0 (do not edit this line) */
