/* Generated By:JJTree: Do not edit this line. ASTExpressaoOu.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpressaoOu extends SimpleNode {
  public ASTExpressaoOu(int id) {
    super(id);
  }

  public ASTExpressaoOu(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=78501f634090ba226603185b973efe4f (do not edit this line) */
