/* Generated By:JJTree: Do not edit this line. ASTExpressaoUnaria.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpressaoUnaria extends SimpleNode {
  public ASTExpressaoUnaria(int id) {
    super(id);
  }

  public ASTExpressaoUnaria(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f06e5e2be5945e70fb069d3b78bdf537 (do not edit this line) */
