/* Generated By:JJTree: Do not edit this line. ASTExpressao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpressao extends SimpleNode {
  public ASTExpressao(int id) {
    super(id);
  }

  public ASTExpressao(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=63e8adbb637fb3845c9b2ef571daff01 (do not edit this line) */
