/* Generated By:JJTree: Do not edit this line. ASTExpressaoRelacional.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpressaoRelacional extends SimpleNode {
  public ASTExpressaoRelacional(int id) {
    super(id);
  }

  public ASTExpressaoRelacional(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d4cbcf5b15a15f9f3872cea03e29fc63 (do not edit this line) */
