/* Generated By:JJTree: Do not edit this line. ASTExecute.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExecute extends SimpleNode {
  public ASTExecute(int id) {
    super(id);
  }

  public ASTExecute(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a78f8cf13a638a04c351ff9f648446a4 (do not edit this line) */
