/* Generated By:JJTree: Do not edit this line. ASTExpressaoPrimaria.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpressaoPrimaria extends SimpleNode {
  public ASTExpressaoPrimaria(int id) {
    super(id);
  }

  public ASTExpressaoPrimaria(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c572ecafe26396b0d3317b1568e9225e (do not edit this line) */
