/* Generated By:JJTree: Do not edit this line. ASTExpressaoAditiva.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpressaoAditiva extends SimpleNode {
  public ASTExpressaoAditiva(int id) {
    super(id);
  }

  public ASTExpressaoAditiva(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f417fe9bc0a12059261536e05a8709a2 (do not edit this line) */
