/* Generated By:JJTree: Do not edit this line. ASTFrequencia.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFrequencia extends SimpleNode {
  public ASTFrequencia(int id) {
    super(id);
  }

  public ASTFrequencia(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=21d5664e61d5f4c8f9f07b6bfbd40d3b (do not edit this line) */
