/* Generated By:JJTree: Do not edit this line. ASTInicializador.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTInicializador extends SimpleNode {
  public ASTInicializador(int id) {
    super(id);
  }

  public ASTInicializador(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ce727a5591fac317ddf5b4b581f39bf7 (do not edit this line) */
