/* Generated By:JJTree: Do not edit this line. ASTLeiaExpressao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTLeiaExpressao extends SimpleNode {
  public ASTLeiaExpressao(int id) {
    super(id);
  }

  public ASTLeiaExpressao(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c9fa697196fe876b472e86eda46bef87 (do not edit this line) */
