/* Generated By:JJTree: Do not edit this line. ASTPrintContent.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPrintContent extends SimpleNode {
  public ASTPrintContent(int id) {
    super(id);
  }

  public ASTPrintContent(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=641b748877e1a16b8cbc0437cf2e2662 (do not edit this line) */
