/* Generated By:JJTree: Do not edit this line. ASTPinMode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPinMode extends SimpleNode {
  public ASTPinMode(int id) {
    super(id);
  }

  public ASTPinMode(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e71d373c392f0d319168dcdf07489e9c (do not edit this line) */
