/* Generated By:JJTree: Do not edit this line. ASTParametros.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTParametros extends SimpleNode {
  public ASTParametros(int id) {
    super(id);
  }

  public ASTParametros(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f38560966c6781c567cbf9f0e695d38d (do not edit this line) */
