/* Generated By:JJTree: Do not edit this line. ASTPinosA.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPinosA extends SimpleNode {
  public ASTPinosA(int id) {
    super(id);
  }

  public ASTPinosA(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=da1453521a957146abb24880bd491cef (do not edit this line) */
