/* Generated By:JJTree: Do not edit this line. ASTPinosPWM.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPinosPWM extends SimpleNode {
  public ASTPinosPWM(int id) {
    super(id);
  }

  public ASTPinosPWM(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ba6b382db91ba9b21d55b5fd8589e8a (do not edit this line) */
