/* Generated By:JJTree: Do not edit this line. ASTPinosD.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPinosD extends SimpleNode {
  public ASTPinosD(int id) {
    super(id);
  }

  public ASTPinosD(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1a921bf2e1fbd7fd669983544f36eaea (do not edit this line) */
