/* Generated By:JJTree: Do not edit this line. ASTPinos.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPinos extends SimpleNode {
  public ASTPinos(int id) {
    super(id);
  }

  public ASTPinos(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=882f2c9f788f6456f62d17c28edc10e3 (do not edit this line) */
