/* Generated By:JJTree: Do not edit this line. ASTRetorne.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTRetorne extends SimpleNode {
  public ASTRetorne(int id) {
    super(id);
  }

  public ASTRetorne(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1a34055a8868bf9be791faaf8ba93e0f (do not edit this line) */
