/* Generated By:JJTree: Do not edit this line. ASTSerialPrint.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTSerialPrint extends SimpleNode {
  public ASTSerialPrint(int id) {
    super(id);
  }

  public ASTSerialPrint(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=28a65a295c3edfde8b0f90de44281e9d (do not edit this line) */
