/* Generated By:JJTree: Do not edit this line. ASTSeSenao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTSeSenao extends SimpleNode {
  public ASTSeSenao(int id) {
    super(id);
  }

  public ASTSeSenao(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aae67ce9089a5b07023a22e515700901 (do not edit this line) */
