/* Generated By:JJTree: Do not edit this line. ASTValorDigital.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTValorDigital extends SimpleNode {
  public ASTValorDigital(int id) {
    super(id);
  }

  public ASTValorDigital(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4cfc3da87d3ca5f47438f5c0893bf638 (do not edit this line) */
