/* Generated By:JavaCC: Do not edit this line. ADSLVisitor.java Version 4.1d1 */
public interface ADSLVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTConfig node, Object data);
  public Object visit(ASTRepita node, Object data);
}
/* JavaCC - OriginalChecksum=475ef6f6acb98d524ac8aef726dc5892 (do not edit this line) */
