/* Generated By:JJTree: Do not edit this line. ASTConfig.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTConfig extends SimpleNode {
  public ASTConfig(int id) {
    super(id);
  }

  public ASTConfig(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2b5e63e3dbe8fb12ca5d6faa39ee20c4 (do not edit this line) */
