/* Generated By:JJTree&JavaCC: Do not edit this line. ADSLConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ADSLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONFIG = 1;
  /** RegularExpression Id. */
  int EXECUTE = 2;
  /** RegularExpression Id. */
  int ENTRADA = 3;
  /** RegularExpression Id. */
  int SAIDA = 4;
  /** RegularExpression Id. */
  int ESPERA = 5;
  /** RegularExpression Id. */
  int MONITOR = 6;
  /** RegularExpression Id. */
  int REPITA = 7;
  /** RegularExpression Id. */
  int FUNCAO = 8;
  /** RegularExpression Id. */
  int RETORNE = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int LEIA = 11;
  /** RegularExpression Id. */
  int ESCREVA = 12;
  /** RegularExpression Id. */
  int ESCREVA_PWM = 13;
  /** RegularExpression Id. */
  int ESCREVA_MON = 14;
  /** RegularExpression Id. */
  int SE = 15;
  /** RegularExpression Id. */
  int SENAO = 16;
  /** RegularExpression Id. */
  int NS = 17;
  /** RegularExpression Id. */
  int MS = 18;
  /** RegularExpression Id. */
  int S = 19;
  /** RegularExpression Id. */
  int MIN = 20;
  /** RegularExpression Id. */
  int H = 21;
  /** RegularExpression Id. */
  int FREQ_300 = 22;
  /** RegularExpression Id. */
  int FREQ_600 = 23;
  /** RegularExpression Id. */
  int FREQ_1200 = 24;
  /** RegularExpression Id. */
  int FREQ_2400 = 25;
  /** RegularExpression Id. */
  int FREQ_4800 = 26;
  /** RegularExpression Id. */
  int FREQ_9600 = 27;
  /** RegularExpression Id. */
  int FREQ_14400 = 28;
  /** RegularExpression Id. */
  int FREQ_19200 = 29;
  /** RegularExpression Id. */
  int FREQ_28800 = 30;
  /** RegularExpression Id. */
  int FREQ_38400 = 31;
  /** RegularExpression Id. */
  int FREQ_57600 = 32;
  /** RegularExpression Id. */
  int FREQ_115200 = 33;
  /** RegularExpression Id. */
  int BYTE = 34;
  /** RegularExpression Id. */
  int INT = 35;
  /** RegularExpression Id. */
  int UNSIGNED_INT = 36;
  /** RegularExpression Id. */
  int LONG = 37;
  /** RegularExpression Id. */
  int UNSIGNED_LONG = 38;
  /** RegularExpression Id. */
  int FLOAT = 39;
  /** RegularExpression Id. */
  int CHAR = 40;
  /** RegularExpression Id. */
  int STRING_TYPE = 41;
  /** RegularExpression Id. */
  int BOOLEAN = 42;
  /** RegularExpression Id. */
  int ASSIGN = 43;
  /** RegularExpression Id. */
  int GT = 44;
  /** RegularExpression Id. */
  int LT = 45;
  /** RegularExpression Id. */
  int BANG = 46;
  /** RegularExpression Id. */
  int TILDE = 47;
  /** RegularExpression Id. */
  int HOOK = 48;
  /** RegularExpression Id. */
  int COLON = 49;
  /** RegularExpression Id. */
  int EQ = 50;
  /** RegularExpression Id. */
  int LE = 51;
  /** RegularExpression Id. */
  int GE = 52;
  /** RegularExpression Id. */
  int NE = 53;
  /** RegularExpression Id. */
  int SC_OR = 54;
  /** RegularExpression Id. */
  int SC_AND = 55;
  /** RegularExpression Id. */
  int CONCAT = 56;
  /** RegularExpression Id. */
  int PLUS = 57;
  /** RegularExpression Id. */
  int MINUS = 58;
  /** RegularExpression Id. */
  int STAR = 59;
  /** RegularExpression Id. */
  int SLASH = 60;
  /** RegularExpression Id. */
  int BIT_AND = 61;
  /** RegularExpression Id. */
  int BIT_OR = 62;
  /** RegularExpression Id. */
  int XOR = 63;
  /** RegularExpression Id. */
  int REM = 64;
  /** RegularExpression Id. */
  int NUM_FLT = 65;
  /** RegularExpression Id. */
  int NUM_INT = 66;
  /** RegularExpression Id. */
  int PINO_ANALOGICO = 67;
  /** RegularExpression Id. */
  int STRING = 68;
  /** RegularExpression Id. */
  int IDENTIFIER = 69;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 70;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 71;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 72;
  /** RegularExpression Id. */
  int LPAREN = 78;
  /** RegularExpression Id. */
  int RPAREN = 79;
  /** RegularExpression Id. */
  int LBRACE = 80;
  /** RegularExpression Id. */
  int RBRACE = 81;
  /** RegularExpression Id. */
  int LBRACKET = 82;
  /** RegularExpression Id. */
  int RBRACKET = 83;
  /** RegularExpression Id. */
  int SEMICOLON = 84;
  /** RegularExpression Id. */
  int COMMA = 85;
  /** RegularExpression Id. */
  int DOT = 86;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Config\"",
    "\"Execute\"",
    "\"Entrada\"",
    "\"Saida\"",
    "\"Espere\"",
    "\"Monitor\"",
    "\"repita\"",
    "\"funcao\"",
    "\"retorne\"",
    "\"void\"",
    "\"Leia\"",
    "\"Escreva\"",
    "\"EscrevaPWM\"",
    "\"EscrevaMon\"",
    "\"se\"",
    "\"senao\"",
    "\"ns\"",
    "\"ms\"",
    "\"s\"",
    "\"min\"",
    "\"h\"",
    "\"300\"",
    "\"600\"",
    "\"1200\"",
    "\"2400\"",
    "\"4800\"",
    "\"9600\"",
    "\"14400\"",
    "\"19200\"",
    "\"28800\"",
    "\"38400\"",
    "\"57600\"",
    "\"115200\"",
    "\"byte\"",
    "\"int\"",
    "\"unsigned int\"",
    "\"long\"",
    "\"unsigned long\"",
    "\"real\"",
    "\"char\"",
    "\"String\"",
    "\"Boolean\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "<NUM_FLT>",
    "<NUM_INT>",
    "<PINO_ANALOGICO>",
    "<STRING>",
    "<IDENTIFIER>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
  };

}
