/* Generated By:JJTree: Do not edit this line. ASTArgumentos.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTArgumentos extends SimpleNode {
  public ASTArgumentos(int id) {
    super(id);
  }

  public ASTArgumentos(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4c6fcc59ef410a30b17e41c084564049 (do not edit this line) */
