/* Generated By:JJTree: Do not edit this line. ASTAtribuicao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAtribuicao extends SimpleNode {
  public ASTAtribuicao(int id) {
    super(id);
  }

  public ASTAtribuicao(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b1757fddbfdc25995a9c38279ed30635 (do not edit this line) */
