/* Generated By:JJTree: Do not edit this line. ASTBlocoSe.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTBlocoSe extends SimpleNode {
  public ASTBlocoSe(int id) {
    super(id);
  }

  public ASTBlocoSe(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8111bb4089869c00aed1a305e0090a99 (do not edit this line) */
