/* Generated By:JJTree: Do not edit this line. ASTChamadaFuncao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTChamadaFuncao extends SimpleNode {
  public ASTChamadaFuncao(int id) {
    super(id);
  }

  public ASTChamadaFuncao(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=55820accb98bbea87b5e8ae01c6dbeaa (do not edit this line) */
