/* Generated By:JJTree: Do not edit this line. ASTCondicao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCondicao extends SimpleNode {
  public ASTCondicao(int id) {
    super(id);
  }

  public ASTCondicao(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d91f3f250c908552386404c3a8982745 (do not edit this line) */
