/* Generated By:JJTree: Do not edit this line. ASTDelay.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDelay extends SimpleNode {
  public ASTDelay(int id) {
    super(id);
  }

  public ASTDelay(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a2212e8edf9f3e10d0c1e997cb93c3e7 (do not edit this line) */
