/* Generated By:JJTree: Do not edit this line. ASTExpressaoMultiplicativa.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpressaoMultiplicativa extends SimpleNode {
  public ASTExpressaoMultiplicativa(int id) {
    super(id);
  }

  public ASTExpressaoMultiplicativa(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=88e2508f49ebb2df74481d0ee1b8622f (do not edit this line) */
