/* Generated By:JJTree: Do not edit this line. ASTExpressaoBooleana.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpressaoBooleana extends SimpleNode {
  public ASTExpressaoBooleana(int id) {
    super(id);
  }

  public ASTExpressaoBooleana(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=67e64e495d79a3c45d4dfba7160a06d6 (do not edit this line) */
