/* Generated By:JJTree: Do not edit this line. ASTExpressaoE.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpressaoE extends SimpleNode {
  public ASTExpressaoE(int id) {
    super(id);
  }

  public ASTExpressaoE(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=40f5e0f58f6e88bf6d32ea43bb01a113 (do not edit this line) */
