/* Generated By:JJTree: Do not edit this line. ASTFreqMonitor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFreqMonitor extends SimpleNode {
  public ASTFreqMonitor(int id) {
    super(id);
  }

  public ASTFreqMonitor(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7fc36af1c9dcbf0cb03e0e92ba798997 (do not edit this line) */
