/* Generated By:JJTree: Do not edit this line. ASTFuncao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFuncao extends SimpleNode {
  public ASTFuncao(int id) {
    super(id);
  }

  public ASTFuncao(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0339e796507c4bce72d9e4c34d8b5464 (do not edit this line) */
