/* Generated By:JJTree: Do not edit this line. ASTFormalComment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFormalComment extends SimpleNode {
  public ASTFormalComment(int id) {
    super(id);
  }

  public ASTFormalComment(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=121e47e10c2ab4b14ee099e43dd54215 (do not edit this line) */
