/* Generated By:JJTree: Do not edit this line. ASTMultiLineComment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMultiLineComment extends SimpleNode {
  public ASTMultiLineComment(int id) {
    super(id);
  }

  public ASTMultiLineComment(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dbbbb140fd9bc1d9aecda87aa68f798c (do not edit this line) */
