/* Generated By:JJTree: Do not edit this line. ASTParametro.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTParametro extends SimpleNode {
  public ASTParametro(int id) {
    super(id);
  }

  public ASTParametro(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c97b6b4ec60e44e8ca714a60b4012cc2 (do not edit this line) */
