/* Generated By:JJTree: Do not edit this line. ASTRead.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTRead extends SimpleNode {
  public ASTRead(int id) {
    super(id);
  }

  public ASTRead(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=96377a3af207bb685e1d4aec8259a48f (do not edit this line) */
