/* Generated By:JJTree: Do not edit this line. ASTRepita.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTRepita extends SimpleNode {
  public ASTRepita(int id) {
    super(id);
  }

  public ASTRepita(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4295cbb64a094cb8025d3fead04520ed (do not edit this line) */
