/* Generated By:JJTree: Do not edit this line. ASTSingleLineComment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTSingleLineComment extends SimpleNode {
  public ASTSingleLineComment(int id) {
    super(id);
  }

  public ASTSingleLineComment(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4165604d71d3ce44e055933fab0bc342 (do not edit this line) */
