/* Generated By:JJTree: Do not edit this line. ASTTiposVar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTTiposVar extends SimpleNode {
  public ASTTiposVar(int id) {
    super(id);
  }

  public ASTTiposVar(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8f7e101c689ac5cf238a7a92f31e04e6 (do not edit this line) */
