/* Generated By:JJTree: Do not edit this line. ASTTipoRetorno.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTTipoRetorno extends SimpleNode {
  public ASTTipoRetorno(int id) {
    super(id);
  }

  public ASTTipoRetorno(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=46131524f81ad339d48fc3629c4066d1 (do not edit this line) */
