/* Generated By:JJTree: Do not edit this line. ASTUnidadeTempo.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTUnidadeTempo extends SimpleNode {
  public ASTUnidadeTempo(int id) {
    super(id);
  }

  public ASTUnidadeTempo(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=857fb322a84160a52a77ab498c9def18 (do not edit this line) */
