/* Generated By:JJTree: Do not edit this line. ASTValorAnalogico.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTValorAnalogico extends SimpleNode {
  public ASTValorAnalogico(int id) {
    super(id);
  }

  public ASTValorAnalogico(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8b13e4f9c6cee2de63201ab458b7e46f (do not edit this line) */
