/* Generated By:JJTree: Do not edit this line. ASTValorNumerico.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTValorNumerico extends SimpleNode {
  public ASTValorNumerico(int id) {
    super(id);
  }

  public ASTValorNumerico(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ff6953653cec15f11dd74a6877c6d88e (do not edit this line) */
