/* Generated By:JJTree: Do not edit this line. ASTValorTempo.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTValorTempo extends SimpleNode {
  public ASTValorTempo(int id) {
    super(id);
  }

  public ASTValorTempo(ADSL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ADSLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4acf542908ee4615074e103d440238a4 (do not edit this line) */
