/* Generated By:JavaCC: Do not edit this line. Imp1ParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Imp1ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int LENGTH = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int VAR = 15;
  /** RegularExpression Id. */
  int COMAND_SKIP = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int READ = 19;
  /** RegularExpression Id. */
  int WRITE = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int THEN = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int LPAREN = 24;
  /** RegularExpression Id. */
  int RPAREN = 25;
  /** RegularExpression Id. */
  int LBRACE = 26;
  /** RegularExpression Id. */
  int RBRACE = 27;
  /** RegularExpression Id. */
  int LBRACKET = 28;
  /** RegularExpression Id. */
  int RBRACKET = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int COMMA = 31;
  /** RegularExpression Id. */
  int DOT = 32;
  /** RegularExpression Id. */
  int LOAD = 33;
  /** RegularExpression Id. */
  int CLEAN = 34;
  /** RegularExpression Id. */
  int NORMALIZE = 35;
  /** RegularExpression Id. */
  int SAVE = 36;
  /** RegularExpression Id. */
  int TRANSFORM = 37;
  /** RegularExpression Id. */
  int AS = 38;
  /** RegularExpression Id. */
  int DROP = 39;
  /** RegularExpression Id. */
  int FILL = 40;
  /** RegularExpression Id. */
  int DROPROWS = 41;
  /** RegularExpression Id. */
  int RENAME = 42;
  /** RegularExpression Id. */
  int REPLACE = 43;
  /** RegularExpression Id. */
  int ADD = 44;
  /** RegularExpression Id. */
  int MULT = 45;
  /** RegularExpression Id. */
  int ATTRIB = 46;
  /** RegularExpression Id. */
  int ASSIGN = 47;
  /** RegularExpression Id. */
  int GT = 48;
  /** RegularExpression Id. */
  int LT = 49;
  /** RegularExpression Id. */
  int BANG = 50;
  /** RegularExpression Id. */
  int TILDE = 51;
  /** RegularExpression Id. */
  int HOOK = 52;
  /** RegularExpression Id. */
  int COLON = 53;
  /** RegularExpression Id. */
  int EQ = 54;
  /** RegularExpression Id. */
  int LE = 55;
  /** RegularExpression Id. */
  int GE = 56;
  /** RegularExpression Id. */
  int NE = 57;
  /** RegularExpression Id. */
  int SC_OR = 58;
  /** RegularExpression Id. */
  int SC_AND = 59;
  /** RegularExpression Id. */
  int CONCAT = 60;
  /** RegularExpression Id. */
  int PLUS = 61;
  /** RegularExpression Id. */
  int MINUS = 62;
  /** RegularExpression Id. */
  int STAR = 63;
  /** RegularExpression Id. */
  int SLASH = 64;
  /** RegularExpression Id. */
  int BIT_AND = 65;
  /** RegularExpression Id. */
  int BIT_OR = 66;
  /** RegularExpression Id. */
  int XOR = 67;
  /** RegularExpression Id. */
  int REM = 68;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 69;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 70;
  /** RegularExpression Id. */
  int HEX_LITERAL = 71;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 72;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 73;
  /** RegularExpression Id. */
  int STRING_LITERAL = 74;
  /** RegularExpression Id. */
  int IDENTIFIER = 75;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"var\"",
    "\"skip\"",
    "\"while\"",
    "\"do\"",
    "\"read\"",
    "\"write\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"LOAD\"",
    "\"CLEAN\"",
    "\"NORMALIZE\"",
    "\"SAVE\"",
    "\"TRANSFORM\"",
    "\"AS\"",
    "\"DROP\"",
    "\"FILL\"",
    "\"DROPROWS\"",
    "\"RENAME\"",
    "\"REPLACE\"",
    "\"ADD\"",
    "\"MULT\"",
    "\":=\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOAT_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
  };

}
